In [1]:

import yfinance as yf
import pandas as pd
import re

In [ ]:
ticker = yf.Ticker('^SPLAC')
print(ticker.)

AttributeError: 'Ticker' object has no attribute 'constituents'

In [2]:
#### Abriendo lista de top 30 en OMX
with open('OMX_Companias.txt', 'r', encoding='utf-8') as file:
    tickers = file.readlines()

tickers = [elem.rstrip('\n') for elem in tickers]
print(tickers)

['AZN.ST', 'ABB.ST', 'INVE-B.ST', 'ATCO-A.ST', 'ATCO-B.ST', 'VOLV-B.ST', 'NDA-SE.ST', 'SAND.ST', 'ERIC-B.ST', 'SWED-A.ST', 'ASSA-B.ST', 'EQT.ST', 'SEB-A.ST', 'EPI-A.ST', 'SAAB-B.ST', 'SHB-A.ST', 'HM-B.ST', 'HEXA-B.ST', 'ALFA.ST', 'INDU-C.ST', 'TELIA.ST', 'ESSITY-B.ST', 'BOL.ST', 'EVO.ST', 'LIFCO-B.ST', 'TEL2-B.ST', 'SKF-B.ST', 'SKA-B.ST', 'ADDT-B.ST', 'NIBE-B.ST']

In [3]:
# ##### Descargar los datos inciales
# start_date = "2003-01-01"
# end_date = "2026-01-01"
# df_crudo = yf.download(tickers, start=start_date, end=end_date, auto_adjust=False)
# df_crudo.to_csv('datos_crudos.csv', index=True, encoding='utf-8')

In [4]:
#### Lectura y Limpieza

### Cargando
df_crudos = pd.read_csv('datos_crudos.csv')

### Limpieza
## Arreglando nombres
nombres = df_crudos.columns.to_list()

for i in range(1,len(nombres)):
    nombres[i] = tickers[(i-1)%len(tickers)] + '.' + nombres[i]

nombres[0] = 'Date'
df_crudos.columns = nombres

### Eliminando primera fila, redundancia
df_crudos = df_crudos.drop(index=0).reset_index(drop=True)



### Cambiando el index del conjunto
df_crudos = df_crudos.set_index('Date',drop=True)


### Verificacion
display(df_crudos.head())   # Visualizar conjunto
df_crudos.info()            # INformacion general
df_crudos.iloc[0]           # Primera fila
df_crudos.index[0]          # Nombre del primer index del cojunto

C:\Users\JP\AppData\Local\Temp\ipykernel_844\2874409947.py:4: DtypeWarning: Columns (0: Adj Close, 1: Adj Close.1, 2: Adj Close.2, 3: Adj Close.3, 4: Adj Close.4, 5: Adj Close.5, 6: Adj Close.6, 7: Adj Close.7, 8: Adj Close.8, 9: Adj Close.9, 10: Adj Close.10, 11: Adj Close.11, 12: Adj Close.12, 13: Adj Close.13, 14: Adj Close.14, 15: Adj Close.15, 16: Adj Close.16, 17: Adj Close.17, 18: Adj Close.18, 19: Adj Close.19, 20: Adj Close.20, 21: Adj Close.21, 22: Adj Close.22, 23: Adj Close.23, 24: Adj Close.24, 25: Adj Close.25, 26: Adj Close.26, 27: Adj Close.27, 28: Adj Close.28, 29: Adj Close.29, 30: Close, 31: Close.1, 32: Close.2, 33: Close.3, 34: Close.4, 35: Close.5, 36: Close.6, 37: Close.7, 38: Close.8, 39: Close.9, 40: Close.10, 41: Close.11, 42: Close.12, 43: Close.13, 44: Close.14, 45: Close.15, 46: Close.16, 47: Close.17, 48: Close.18, 49: Close.19, 50: Close.20, 51: Close.21, 52: Close.22, 53: Close.23, 54: Close.24, 55: Close.25, 56: Close.26, 57: Close.27, 58: Close.28, 59: Close.29, 60: High, 61: High.1, 62: High.2, 63: High.3, 64: High.4, 65: High.5, 66: High.6, 67: High.7, 68: High.8, 69: High.9, 70: High.10, 71: High.11, 72: High.12, 73: High.13, 74: High.14, 75: High.15, 76: High.16, 77: High.17, 78: High.18, 79: High.19, 80: High.20, 81: High.21, 82: High.22, 83: High.23, 84: High.24, 85: High.25, 86: High.26, 87: High.27, 88: High.28, 89: High.29, 90: Low, 91: Low.1, 92: Low.2, 93: Low.3, 94: Low.4, 95: Low.5, 96: Low.6, 97: Low.7, 98: Low.8, 99: Low.9, 100: Low.10, 101: Low.11, 102: Low.12, 103: Low.13, 104: Low.14, 105: Low.15, 106: Low.16, 107: Low.17, 108: Low.18, 109: Low.19, 110: Low.20, 111: Low.21, 112: Low.22, 113: Low.23, 114: Low.24, 115: Low.25, 116: Low.26, 117: Low.27, 118: Low.28, 119: Low.29, 120: Open, 121: Open.1, 122: Open.2, 123: Open.3, 124: Open.4, 125: Open.5, 126: Open.6, 127: Open.7, 128: Open.8, 129: Open.9, 130: Open.10, 131: Open.11, 132: Open.12, 133: Open.13, 134: Open.14, 135: Open.15, 136: Open.16, 137: Open.17, 138: Open.18, 139: Open.19, 140: Open.20, 141: Open.21, 142: Open.22, 143: Open.23, 144: Open.24, 145: Open.25, 146: Open.26, 147: Open.27, 148: Open.28, 149: Open.29, 150: Volume, 151: Volume.1, 152: Volume.2, 153: Volume.3, 154: Volume.4, 155: Volume.5, 156: Volume.6, 157: Volume.7, 158: Volume.8, 159: Volume.9, 160: Volume.10, 161: Volume.11, 162: Volume.12, 163: Volume.13, 164: Volume.14, 165: Volume.15, 166: Volume.16, 167: Volume.17, 168: Volume.18, 169: Volume.19, 170: Volume.20, 171: Volume.21, 172: Volume.22, 173: Volume.23, 174: Volume.24, 175: Volume.25, 176: Volume.26, 177: Volume.27, 178: Volume.28, 179: Volume.29) have mixed types. Specify dtype option on import or set low_memory=False.
  df_crudos = pd.read_csv('datos_crudos.csv')

,AZN.ST.Adj Close,ABB.ST.Adj Close.1,INVE-B.ST.Adj Close.2,ATCO-A.ST.Adj Close.3,ATCO-B.ST.Adj Close.4,VOLV-B.ST.Adj Close.5,NDA-SE.ST.Adj Close.6,SAND.ST.Adj Close.7,ERIC-B.ST.Adj Close.8,SWED-A.ST.Adj Close.9,...,TELIA.ST.Volume.20,ESSITY-B.ST.Volume.21,BOL.ST.Volume.22,EVO.ST.Volume.23,LIFCO-B.ST.Volume.24,TEL2-B.ST.Volume.25,SKF-B.ST.Volume.26,SKA-B.ST.Volume.27,ADDT-B.ST.Volume.28,NIBE-B.ST.Volume.29
Date,,,,,,,,,,,,,,,,,,,,,
2003-01-01,17.680892944335938,1.2537856101989746,10.125161170959473,20.894878387451172,2.7186105251312256,2.1777186393737793,254.4774932861328,5.802927494049072,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2003-01-02,19.598102569580078,1.2537856101989746,10.052838325500488,21.839874267578125,2.9105119705200195,2.3539092540740967,253.2301025390625,6.044716835021973,NaN,NaN,...,209187,14945504,4189601,3484337,567608,7809552,1516860,3883272,6724829,21896925
2003-01-03,19.52709197998047,1.2328892946243286,9.980515480041504,22.259870529174805,3.0144598484039307,2.4596240520477295,254.06170654296875,6.447697639465332,NaN,NaN,...,1118851,23697281,4677152,5053354,922355,5986992,2090083,2377278,6839676,19311075
2003-01-06,19.52709197998047,1.2328892946243286,9.980515480041504,22.259870529174805,3.0144598484039307,2.4596240520477295,254.06170654296875,6.447697639465332,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2003-01-07,19.172054290771484,1.1910960674285889,9.908196449279785,22.67987632751465,2.990471363067627,2.438481330871582,246.16128540039062,6.568592548370361,NaN,NaN,...,242575,29908267,7304279,10019741,860154,11782592,2190290,2206966,9118632,26731900

<class 'pandas.DataFrame'>
Index: 5816 entries, 2003-01-01 to 2025-12-30
Columns: 180 entries, AZN.ST.Adj Close to NIBE-B.ST.Volume.29
dtypes: object(180)
memory usage: 8.0+ MB

'2003-01-01'

In [5]:
#### Seleccionando columnas adecuadas
bool_lista = df_crudos.columns.str.contains(r'Adj Close')
precios_nom = []
for col_nom, bol in zip(df_crudos.columns.to_list(), bool_lista):
    if not bol: break
    precios_nom.append(col_nom)

print(precios_nom)

['AZN.ST.Adj Close', 'ABB.ST.Adj Close.1', 'INVE-B.ST.Adj Close.2', 'ATCO-A.ST.Adj Close.3', 'ATCO-B.ST.Adj Close.4', 'VOLV-B.ST.Adj Close.5', 'NDA-SE.ST.Adj Close.6', 'SAND.ST.Adj Close.7', 'ERIC-B.ST.Adj Close.8', 'SWED-A.ST.Adj Close.9', 'ASSA-B.ST.Adj Close.10', 'EQT.ST.Adj Close.11', 'SEB-A.ST.Adj Close.12', 'EPI-A.ST.Adj Close.13', 'SAAB-B.ST.Adj Close.14', 'SHB-A.ST.Adj Close.15', 'HM-B.ST.Adj Close.16', 'HEXA-B.ST.Adj Close.17', 'ALFA.ST.Adj Close.18', 'INDU-C.ST.Adj Close.19', 'TELIA.ST.Adj Close.20', 'ESSITY-B.ST.Adj Close.21', 'BOL.ST.Adj Close.22', 'EVO.ST.Adj Close.23', 'LIFCO-B.ST.Adj Close.24', 'TEL2-B.ST.Adj Close.25', 'SKF-B.ST.Adj Close.26', 'SKA-B.ST.Adj Close.27', 'ADDT-B.ST.Adj Close.28', 'NIBE-B.ST.Adj Close.29']

In [6]:
df_precios=df_crudos[precios_nom].copy()

print(len(df_precios))
print(df_precios.isna().sum())

5816
AZN.ST.Adj Close               0
ABB.ST.Adj Close.1             0
INVE-B.ST.Adj Close.2          0
ATCO-A.ST.Adj Close.3          0
ATCO-B.ST.Adj Close.4          0
VOLV-B.ST.Adj Close.5          0
NDA-SE.ST.Adj Close.6          0
SAND.ST.Adj Close.7            0
ERIC-B.ST.Adj Close.8       3923
SWED-A.ST.Adj Close.9       4240
ASSA-B.ST.Adj Close.10         0
EQT.ST.Adj Close.11         3668
SEB-A.ST.Adj Close.12       3105
EPI-A.ST.Adj Close.13          0
SAAB-B.ST.Adj Close.14         0
SHB-A.ST.Adj Close.15          0
HM-B.ST.Adj Close.16           0
HEXA-B.ST.Adj Close.17      3026
ALFA.ST.Adj Close.18           0
INDU-C.ST.Adj Close.19         0
TELIA.ST.Adj Close.20          0
ESSITY-B.ST.Adj Close.21       0
BOL.ST.Adj Close.22            0
EVO.ST.Adj Close.23            0
LIFCO-B.ST.Adj Close.24        0
TEL2-B.ST.Adj Close.25         0
SKF-B.ST.Adj Close.26          0
SKA-B.ST.Adj Close.27          0
ADDT-B.ST.Adj Close.28         0
NIBE-B.ST.Adj Close.29         0
dtype: int64

In [7]:
#### Limpiando datos
### Copiando datos
df_precios=df_crudos[precios_nom].copy()

### Cambiando nombre de columnas
tickers = [elem.split('.')[0] for elem in tickers]
df_precios.columns = tickers

### Eliminando columnas que no tenga suficiente datos
max_dias = len(df_precios)
THRESH = 0.5    #Cantidad de dias/datos originales dispuesto a borrar
for col in df_precios.columns:
    if df_precios[col].isna().sum() > THRESH * max_dias:
        df_precios = df_precios.drop(col, axis=1)


### Hacer forward fill y eliminar Nans
df_precios = df_precios.ffill().dropna()

### Transformat tipos de datos de str a float
df_precios = df_precios.astype(float)

print(len(df_precios.columns))
display(df_precios.head())

25

,AZN,ABB,INVE-B,ATCO-A,ATCO-B,VOLV-B,NDA-SE,SAND,ASSA-B,EPI-A,...,TELIA,ESSITY-B,BOL,EVO,LIFCO-B,TEL2-B,SKF-B,SKA-B,ADDT-B,NIBE-B
Date,,,,,,,,,,,,,,,,,,,,,
2003-01-01,17.680893,1.253786,10.125161,20.894878,2.718611,2.177719,254.477493,5.802927,16.577457,1.417099,...,13.689431,17.920635,12.770103,9.506189,16.124863,25.729830,21.763048,12.203835,8.371820,9.991637
2003-01-02,19.598103,1.253786,10.052838,21.839874,2.910512,2.353909,253.230103,6.044717,18.343906,1.422233,...,13.546830,19.026281,13.826938,10.038865,16.441042,27.152927,22.502565,12.177365,8.499438,10.695272
2003-01-03,19.527092,1.232889,9.980515,22.259871,3.014460,2.459624,254.061707,6.447698,18.479790,1.447905,...,13.546830,19.717308,13.915007,9.915938,16.915300,27.266779,22.396921,12.389146,8.729154,10.836000
2003-01-06,19.527092,1.232889,9.980515,22.259871,3.014460,2.459624,254.061707,6.447698,18.479790,1.447905,...,13.546830,19.717308,13.915007,9.915938,16.915300,27.266779,22.396921,12.389146,8.729154,10.836000
2003-01-07,19.172054,1.191096,9.908196,22.679876,2.990471,2.438481,246.161285,6.568593,19.838602,1.458174,...,13.119037,19.717308,13.474658,9.915938,17.231472,27.266779,22.291273,12.389146,8.524965,10.871184

In [11]:
#### Rendimientos y Medianos
### Transformando precios en rentabilidad
df_rendis = df_precios.pct_change().dropna()

### Creando columna de medianos
df_rendis['Median'] = df_rendis.median(axis=1)

display(df_rendis.head())
df_rendis.info

,AZN,ABB,INVE-B,ATCO-A,ATCO-B,VOLV-B,NDA-SE,SAND,ASSA-B,EPI-A,...,ESSITY-B,BOL,EVO,LIFCO-B,TEL2-B,SKF-B,SKA-B,ADDT-B,NIBE-B,Median
Date,,,,,,,,,,,,,,,,,,,,,
2003-01-02,0.108434,0.000000,-0.007143,0.045226,0.070588,0.080906,-0.004902,0.041667,0.106557,0.003623,...,0.061697,0.082759,0.056035,0.019608,0.055309,0.033980,-0.002169,0.015244,0.070422,0.041667
2003-01-03,-0.003623,-0.016667,-0.007194,0.019231,0.035715,0.044910,0.003284,0.066667,0.007408,0.018051,...,0.036320,0.006369,-0.012245,0.028846,0.004193,-0.004695,0.017391,0.027027,0.013158,0.007408
2003-01-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2003-01-07,-0.018182,-0.033899,-0.007246,0.018868,-0.007958,-0.008596,-0.031096,0.018750,0.073530,0.007092,...,0.000000,-0.031646,0.000000,0.018691,0.000000,-0.004717,0.000000,-0.023392,0.003247,0.000000
2003-01-08,-0.044444,0.017544,-0.029197,-0.037037,-0.021390,-0.023121,-0.021960,-0.030675,-0.034247,-0.003521,...,-0.056075,-0.019608,-0.012397,-0.027523,-0.045929,0.004739,-0.012821,-0.032934,-0.032363,-0.027523

<bound method DataFrame.info of                  AZN       ABB    INVE-B    ATCO-A    ATCO-B    VOLV-B  \
Date
2003-01-02  0.108434  0.000000 -0.007143  0.045226  0.070588  0.080906
2003-01-03 -0.003623 -0.016667 -0.007194  0.019231  0.035715  0.044910
2003-01-06  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
2003-01-07 -0.018182 -0.033899 -0.007246  0.018868 -0.007958 -0.008596
2003-01-08 -0.044444  0.017544 -0.029197 -0.037037 -0.021390 -0.023121
...              ...       ...       ...       ...       ...       ...
2025-12-19  0.006484  0.006180  0.008539  0.002254  0.005208  0.000340
2025-12-22  0.002928  0.002457  0.001954  0.000562  0.002743  0.004755
2025-12-23  0.004380 -0.003676 -0.000217 -0.001685  0.002736 -0.001014
2025-12-29 -0.000581  0.004305  0.006069  0.006472  0.003637  0.006091
2025-12-30  0.000291  0.002449  0.003231  0.003355  0.003020  0.002355

              NDA-SE      SAND    ASSA-B     EPI-A  ...  ESSITY-B       BOL  \
Date                                                ...
2003-01-02 -0.004902  0.041667  0.106557  0.003623  ...  0.061697  0.082759
2003-01-03  0.003284  0.066667  0.007408  0.018051  ...  0.036320  0.006369
2003-01-06  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
2003-01-07 -0.031096  0.018750  0.073530  0.007092  ...  0.000000 -0.031646
2003-01-08 -0.021960 -0.030675 -0.034247 -0.003521  ... -0.056075 -0.019608
...              ...       ...       ...       ...  ...       ...       ...
2025-12-19  0.009795  0.011985  0.003329  0.001873  ...  0.002033  0.010220
2025-12-22 -0.005879  0.002409  0.000664  0.003738  ...  0.005073 -0.000778
2025-12-23  0.004731  0.005206 -0.008179 -0.004190  ... -0.003028  0.000779
2025-12-29  0.002060  0.010757  0.003120  0.012623  ...  0.010462  0.003632
2025-12-30  0.000587  0.015372  0.006443  0.011080  ...  0.004008  0.008529

                 EVO   LIFCO-B    TEL2-B     SKF-B     SKA-B    ADDT-B  \
Date
2003-01-02  0.056035  0.019608  0.055309  0.033980 -0.002169  0.015244
2003-01-03 -0.012245  0.028846  0.004193 -0.004695  0.017391  0.027027
2003-01-06  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
2003-01-07  0.000000  0.018691  0.000000 -0.004717  0.000000 -0.023392
2003-01-08 -0.012397 -0.027523 -0.045929  0.004739 -0.012821 -0.032934
...              ...       ...       ...       ...       ...       ...
2025-12-19  0.010290 -0.001597  0.000828  0.011535  0.001308 -0.001035
2025-12-22 -0.000755  0.011600  0.002894  0.000950 -0.007838 -0.001295
2025-12-23  0.007173 -0.005931 -0.000412  0.008544  0.006254  0.009857
2025-12-29 -0.004498 -0.000795  0.007835 -0.002196  0.004907  0.008220
2025-12-30  0.011672  0.004379  0.005728  0.009748  0.006185  0.003312

              NIBE-B    Median
Date
2003-01-02  0.070422  0.041667
2003-01-03  0.013158  0.007408
2003-01-06  0.000000  0.000000
2003-01-07  0.003247  0.000000
2003-01-08 -0.032363 -0.027523
...              ...       ...
2025-12-19 -0.000679  0.003329
2025-12-22 -0.004759  0.001954
2025-12-23 -0.003074  0.000779
2025-12-29  0.006509  0.004907
2025-12-30  0.007148  0.005728

[5815 rows x 26 columns]>

In [ ]:
##### Creando los labels
for nombre in df_rendis.columns.to_list()[:-1]:
    comparacion = df_rendis[nombre] > df_rendis['Median']
    df_rendis['label_' + nombre] = comparacion.astype(int)

display(df_rendis.head())
df_rendis.info

,AZN,ABB,INVE-B,ATCO-A,ATCO-B,VOLV-B,NDA-SE,SAND,ASSA-B,EPI-A,...,label_TELIA,label_ESSITY-B,label_BOL,label_EVO,label_LIFCO-B,label_TEL2-B,label_SKF-B,label_SKA-B,label_ADDT-B,label_NIBE-B
Date,,,,,,,,,,,,,,,,,,,,,
2003-01-02,0.108434,0.000000,-0.007143,0.045226,0.070588,0.080906,-0.004902,0.041667,0.106557,0.003623,...,0,1,1,1,0,1,0,0,0,1
2003-01-03,-0.003623,-0.016667,-0.007194,0.019231,0.035715,0.044910,0.003284,0.066667,0.007408,0.018051,...,0,1,0,0,1,0,0,1,1,1
2003-01-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
2003-01-07,-0.018182,-0.033899,-0.007246,0.018868,-0.007958,-0.008596,-0.031096,0.018750,0.073530,0.007092,...,0,0,0,0,1,0,0,0,0,1
2003-01-08,-0.044444,0.017544,-0.029197,-0.037037,-0.021390,-0.023121,-0.021960,-0.030675,-0.034247,-0.003521,...,1,0,1,1,0,0,1,1,0,0

<bound method DataFrame.info of                  AZN       ABB    INVE-B    ATCO-A    ATCO-B    VOLV-B  \
Date
2003-01-02  0.108434  0.000000 -0.007143  0.045226  0.070588  0.080906
2003-01-03 -0.003623 -0.016667 -0.007194  0.019231  0.035715  0.044910
2003-01-06  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
2003-01-07 -0.018182 -0.033899 -0.007246  0.018868 -0.007958 -0.008596
2003-01-08 -0.044444  0.017544 -0.029197 -0.037037 -0.021390 -0.023121
...              ...       ...       ...       ...       ...       ...
2025-12-19  0.006484  0.006180  0.008539  0.002254  0.005208  0.000340
2025-12-22  0.002928  0.002457  0.001954  0.000562  0.002743  0.004755
2025-12-23  0.004380 -0.003676 -0.000217 -0.001685  0.002736 -0.001014
2025-12-29 -0.000581  0.004305  0.006069  0.006472  0.003637  0.006091
2025-12-30  0.000291  0.002449  0.003231  0.003355  0.003020  0.002355

              NDA-SE      SAND    ASSA-B     EPI-A  ...  label_TELIA  \
Date                                                ...
2003-01-02 -0.004902  0.041667  0.106557  0.003623  ...            0
2003-01-03  0.003284  0.066667  0.007408  0.018051  ...            0
2003-01-06  0.000000  0.000000  0.000000  0.000000  ...            0
2003-01-07 -0.031096  0.018750  0.073530  0.007092  ...            0
2003-01-08 -0.021960 -0.030675 -0.034247 -0.003521  ...            1
...              ...       ...       ...       ...  ...          ...
2025-12-19  0.009795  0.011985  0.003329  0.001873  ...            1
2025-12-22 -0.005879  0.002409  0.000664  0.003738  ...            1
2025-12-23  0.004731  0.005206 -0.008179 -0.004190  ...            1
2025-12-29  0.002060  0.010757  0.003120  0.012623  ...            0
2025-12-30  0.000587  0.015372  0.006443  0.011080  ...            1

            label_ESSITY-B  label_BOL  label_EVO  label_LIFCO-B  label_TEL2-B  \
Date
2003-01-02               1          1          1              0             1
2003-01-03               1          0          0              1             0
2003-01-06               0          0          0              0             0
2003-01-07               0          0          0              1             0
2003-01-08               0          1          1              0             0
...                    ...        ...        ...            ...           ...
2025-12-19               0          1          1              0             0
2025-12-22               1          0          0              1             1
2025-12-23               0          0          1              0             0
2025-12-29               1          0          0              0             1
2025-12-30               0          1          1              0             0

            label_SKF-B  label_SKA-B  label_ADDT-B  label_NIBE-B
Date
2003-01-02            0            0             0             1
2003-01-03            0            1             1             1
2003-01-06            0            0             0             0
2003-01-07            0            0             0             1
2003-01-08            1            1             0             0
...                 ...          ...           ...           ...
2025-12-19            1            0             0             0
2025-12-22            0            0             0             0
2025-12-23            1            1             1             0
2025-12-29            0            0             1             1
2025-12-30            1            1             0             1

[5815 rows x 51 columns]>

In [25]:
#### Exportacion de datos

df_rendis.to_csv('datos_procesados.csv')